/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dispatch;

/**
 *
 * @author gbian
 */
public class InitMainPanel extends javax.swing.JFrame {

    /**
     * Creates new form InitMainPanel
     * @param dispatch
     * @param panel
     */
    public InitMainPanel(Dispatch dispatch, MainPanel panel) 
    {
        m_dispatch = dispatch;
        m_panel = panel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        initMembersButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Screen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvas1.setVisible(false);

        initMembersButton.setBackground(new java.awt.Color(0, 255, 64));
        initMembersButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        initMembersButton.setText("ENTREZ LES NOMS");
        initMembersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        initMembersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initMembersButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 0, 0));
        quitButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        quitButton.setText("QUITTER");
        quitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        Screen.setEditable(false);
        Screen.setColumns(20);
        Screen.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Screen.setRows(5);
        Screen.setText("   ************* LOGICIEL DE REPARTITION *************\n\n              \n\t\t Bonjour mon Commandant !\n\n\t      Chargement du logiciel terminé.\n\n\n\t  Cliquez sur \"ENTREZ LES NOMS\" pour enter\n     les noms des leaders et membres de squads ou sur\n                 \"QUITTER\" pour quitter.");
        jScrollPane1.setViewportView(Screen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(initMembersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initMembersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void initMembersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initMembersButtonActionPerformed
        InitMembersPanel panel = new InitMembersPanel(m_dispatch, m_panel);
        panel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_initMembersButtonActionPerformed

    private final Dispatch m_dispatch;
    private final MainPanel m_panel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Screen;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton initMembersButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
